services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=fiap
      - MONGO_INITDB_ROOT_PASSWORD=fiap123456
    networks:
      - techchallenge-worker-persistency_custom_network

  contact_integration_worker:
    build:
      context: .
      dockerfile: src/Postech.GroupEight.ContactIntegration.Worker/Dockerfile
    container_name: contact_integration_worker
    restart: always
    ports:
      - "5678:5678"
    environment:
      ASPNETCORE_ENVIRONMENT: "Docker"
      MONGO_CONNECTION_STRING: "mongodb://fiap:fiap123456@mongodb:27017/admin"
      RABBITMQ_HOST: "rabbitmq"
      RABBITMQ_PORT: "5672"
    depends_on:
      - mongodb
    networks:
      - techchallenge-worker-persistency_custom_network

networks:
  techchallenge-worker-persistency_custom_network:
    external: true