services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=fiap
      - MONGO_INITDB_ROOT_PASSWORD=fiap123456
    networks:
      - app-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=Admin*123
    networks:
      - app-network

  worker:
    build:
      context: .
      dockerfile: src/Postech.GroupEight.ContactIntegration.Worker/Dockerfile
    container_name: contact_integration_worker
    restart: always
    ports:
      - "5005:8080"
      - "5678:5678"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      MONGO_CONNECTION_STRING: "mongodb://fiap:fiap123456@mongodb:27017/admin"
      RABBITMQ_HOST: "rabbitmq"
      RABBITMQ_PORT: "5672"
    depends_on:
      - mongodb
      - rabbitmq
    networks:
      - app-network

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    networks:
      - app-network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - app-network

networks:
  app-network:
    external: true
