services:
  # MongoDB Database
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=fiap
      - MONGO_INITDB_ROOT_PASSWORD=fiap123456

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "15672:15672"  # Porta de gerenciamento do RabbitMQ
      - "5672:5672"    # Porta de comunicação do RabbitMQ
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

  worker:
    build:
      context: .
      dockerfile: src/Postech.GroupEight.ContactIntegration.Worker/Dockerfile
    container_name: contact_integration_worker
    restart: always
    ports:
      - "5005:8080"  # Porta do worker
      - "5678:5678"  # Porta do Prometheus 
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      MONGO_CONNECTION_STRING: "mongodb://fiap:fiap123456@mongodb:27017/admin"
      RABBITMQ_HOST: "rabbitmq"
      RABBITMQ_PORT: "5672" 
    depends_on:
      - mongodb
      - rabbitmq

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin

networks:
  app-network:
    driver: bridge

volumes:
  prometheus_data: {}
  grafana_data: {}