{
 "title": "Contact-Integration-Worker",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Total de eventos de criação de contato",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "contact_create_events_total" }
   ]
  },
  {
   "title": "Total de eventos de atualização de contato",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "contact_update_events_total" }
   ]
  },
  {
   "title": "Total de eventos de exclusão de contato",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 11, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "contact_delete_events_total" }
   ]
  },
  {
   "title": "Total de Mensagens Recebidas (RabbitMQ)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 0 },
   "targets": [
    {
     "expr": "sum(masstransit_messaging_masstransit_receive{messaging_masstransit_service=\"Postech.GroupEight.ContactIntegration.Worker\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tempo de Consumo das Mensagens",
   "type": "timeseries",
   "description": "Tempo decorrido gasto consumindo uma mensagem, em milissegundos",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(masstransit_messaging_masstransit_consume_duration_bucket{messaging_masstransit_service=\"Postech.GroupEight.ContactIntegration.Worker\"}[5m])) by (le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Duração da Entrega das Mensagens",
   "type": "timeseries",
   "description": "Tempo decorrido entre o envio da mensagem e o seu consumo, em milissegundos.",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 6 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(masstransit_messaging_masstransit_delivery_duration_bucket{messaging_masstransit_service=\"Postech.GroupEight.ContactIntegration.Worker\"}[5m])) by (le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Quantidade de requisições GET API contactFind",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "http_requests_received_total{endpoint=\"/contacts\", method=\"GET\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Mensagens Recebidas Ativas (RabbitMQ)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 14 },
   "targets": [
    {
     "expr": "sum(masstransit_messaging_masstransit_receive_active{messaging_masstransit_service=\"Postech.GroupEight.ContactIntegration.Worker\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}