apiVersion: apps/v1
kind: Deployment
metadata:
  name: contact-integration-worker-deployment
  labels:
    app: contact-integration-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: contact-integration-worker
  template:
    metadata:
      labels:
        app: contact-integration-worker
    spec:
      containers:
      - name: container-contact-integration-worker
        image: brenojgomes/contactintegration_worker:3
        ports:
        - containerPort: 5266
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Docker"
        - name: MONGO_CONNECTION_STRING
          value: "mongodb://fiap:fiap123456@mongodb-service:27017/admin"
        - name: RABBITMQ_HOST
          value: "rabbitmq"
        - name: RABBITMQ_PORT
          value: "5672"


---
apiVersion: v1
kind: Service
metadata:
  name: contact-integration-worker-service
  labels:
    app: contact-integration-worker
spec:
  selector:
    app: contact-integration-worker
  type: ClusterIP
  ports:
    - port: 80 
      targetPort: 5678
